---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/20/2023 10:09 PM
---

---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/20/2023 10:09 PM
---

---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/20/2023 10:09 PM
---
return {
    run = {
        main =                     {
            filename = "__erm_toss_hd_assets__/graphics/entity/units/carrier/carrier-run.png",
            width = 515,
            height = 496,
            frame_count = 1,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.4,
            animation_speed = 0.4,
        },
        shadow = {
            shift = { 6, 0 }
        },
        glow =                         {
            filename = "__erm_toss_hd_assets__/graphics/entity/units/carrier/carrier-effect.png",
            width = 515,
            height = 506,
            frame_count = 1,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.4,
            animation_speed = 0.4,
            blend_mode = "additive",
            tint = { r = 110, g = 210, b = 255, a = 255 }
        },
        team = {
            filename = "__erm_toss_hd_assets__/graphics/entity/units/carrier/carrier-run_teamcolour.png",
            width = 515,
            height = 496,
            frame_count = 1,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.4,
            animation_speed = 0.4,
        }
    }
}