---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/20/2023 10:09 PM
---

---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/20/2023 10:09 PM
---

return {
    run = {
        main =                     {
            filename = "__erm_toss_hd_assets__/graphics/entity/units/corsair/corsair-run.png",
            width = 248,
            height = 232,
            frame_count = 1,
            repeat_count = 2,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.325,
            animation_speed = 0.4,
        },
        shadow = {
            shift = { 4, 0 }
        },
        glow =                         {
            filename = "__erm_toss_hd_assets__/graphics/entity/units/corsair/corsair-effect.png",
            width = 246,
            height = 232,
            frame_count = 2,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.325,
            animation_speed = 0.4,
            blend_mode = "additive",
            --    shift = util.by_pixel(-4, -4),
            tint = { r = 110, g = 210, b = 255, a = 255 }
        },
        team =                         {
            filename = "__erm_toss_hd_assets__/graphics/entity/units/corsair/corsair_teamcolour.png",
            width = 248,
            height = 232,
            frame_count = 1,
            repeat_count = 2,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.325,
            animation_speed = 0.4,
            draw_as_glow = true,
        },
    },
    attack = {
        main =                         {
            filename = "__erm_toss_hd_assets__/graphics/entity/units/corsair/corsair-attack.png",
            width = 248,
            height = 232,
            frame_count = 4,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.325,
            animation_speed = 0.4,
        },
        shadow = {
            shift = { 4, 0 }
        },
        glow = {
            filename = "__erm_toss_hd_assets__/graphics/entity/units/corsair/corsair-effect.png",
            width = 246,
            height = 232,
            frame_count = 2,
            repeat_count = 2,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.325,
            animation_speed = 0.4,
            blend_mode = "additive",
            tint = { r = 110, g = 210, b = 255, a = 255 },
        },
        team =                         {
            filename = "__erm_toss_hd_assets__/graphics/entity/units/corsair/corsair_teamcolour.png",
            width = 248,
            height = 232,
            frame_count = 1,
            repeat_count = 4,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.325,
            animation_speed = 0.4,
            draw_as_glow = true,
        },
    }
}