---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/20/2023 10:09 PM
---

---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/20/2023 10:09 PM
---
local ERM_UnitTint = require('__enemyracemanager__/lib/rig/unit_tint')
return {
    run = {
        main =                     {
            filename = "__erm_toss_hd_assets__/graphics/entity/units/corsair/corsair-run.png",
            width = 250,
            height = 234,
            frame_count = 1,
            repeat_count = 2,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.325,
            animation_speed = 0.5,
        },
        shadow = {
            shift = { 4, 0 }
        },
        glow =                         {
            filename = "__erm_toss_hd_assets__/graphics/entity/units/corsair/corsair-effect.png",
            width = 246,
            height = 232,
            frame_count = 2,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.325,
            animation_speed = 0.5,
            blend_mode = "additive",
            --    shift = util.by_pixel(-4, -4),
            tint = ERM_UnitTint.tint_blue_flame_burner()
        }
    },
    attack = {
        main =                         {
            filename = "__erm_toss_hd_assets__/graphics/entity/units/corsair/corsair-attack.png",
            width = 248,
            height = 232,
            frame_count = 4,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.325,
            animation_speed = 0.5,
        },
        shadow = {
            shift = { 4, 0 }
        },
        glow = {
            filename = "__erm_toss_hd_assets__/graphics/entity/units/corsair/corsair-effect.png",
            width = 246,
            height = 232,
            frame_count = 2,
            repeat_count = 2,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.325,
            animation_speed = 0.5,
            blend_mode = "additive",
            tint = ERM_UnitTint.tint_blue_flame_burner(),
        }
    }
}