---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/20/2023 10:09 PM
---

return {
    attack = {
        main =                         {
            filename = "__erm_toss_hd_assets__/graphics/entity/units/darktemplar/darktemplar-attack.png",
            width = 353,
            height = 268,
            frame_count = 9,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.3125,
            animation_speed = 0.4
        },
        shadow = {
            shift = { 0.2, 0 }
        },
        team = {
            filename = "__erm_toss_hd_assets__/graphics/entity/units/darktemplar/darktemplar-attack_teamcolour.png",
            width = 353,
            height = 268,
            frame_count = 9,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.3125,
            animation_speed = 0.4
        }
    },
    run = {
        main =                     {
            filename = "__erm_toss_hd_assets__/graphics/entity/units/darktemplar/darktemplar-run.png",
            width = 353,
            height = 268,
            frame_count = 8,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.3125,
            animation_speed = 0.4,
        },
        shadow = {
            shift = { 0.2, 0 }
        },
        team = {
            filename = "__erm_toss_hd_assets__/graphics/entity/units/darktemplar/darktemplar-run_teamcolour.png",
            width = 353,
            height = 268,
            frame_count = 8,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.3125,
            animation_speed = 0.4,
        }
    }
}