---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/20/2023 10:09 PM
---

return {
    attack = {
        main =                         {
            filename = "__erm_toss_hd_assets__/graphics/entity/units/dragoon/dragoon-attack.png",
            width = 388,
            height = 376,
            frame_count = 8,
            axially_symmetrical = false,
            direction_count = 1,
            run_mode = "forward-then-backward",
            scale = 0.325,
            animation_speed = 0.5,
        },
        shadow = {
            shift = { 0.2, 0 }
        }
    },
    run = {
        main =                         {
            filename = "__erm_toss_hd_assets__/graphics/entity/units/dragoon/dragoon-run.png",
            width = 388,
            height = 376,
            frame_count = 9,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.325,
            animation_speed = 0.5,
        },
        shadow = {
            shift = { 0.2, 0 }
        }
    },
    corpse = {
        main = {
            filename = "__erm_toss_hd_assets__/graphics/entity/units/dragoon/dragoon-death.png",
            width = 388,
            height = 376,
            frame_count = 7,
            direction_count = 1,
            axially_symmetrical = false,
            scale = 0.325,
            animation_speed = 0.2
        }
    }
}