---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/20/2023 10:09 PM
---

return {
    run = {
        main = {
            filename = "__erm_toss_hd_assets__/graphics/entity/units/interceptor/interceptor-run.png",
            width = 141,
            height = 136,
            frame_count = 1,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.375,
            animation_speed = 0.5,
        },
        shadow = {
            shift = { 4, 0 }
        },
        team = {
            filename = "__erm_toss_hd_assets__/graphics/entity/units/interceptor/interceptor_teamcolour.png",
            width = 141,
            height = 136,
            frame_count = 1,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.375,
            animation_speed = 0.5,
        }
    },
    attack = {
        main =                         {
            filename = "__erm_toss_hd_assets__/graphics/entity/units/interceptor/interceptor-attack.png",
            width = 141,
            height = 136,
            frame_count = 1,
            repeat_count = 3,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.375,
            animation_speed = 0.5,
        },
        shadow = {
            shift = { 4, 0 }
        },
        team = {
            filename = "__erm_toss_hd_assets__/graphics/entity/units/interceptor/interceptor_teamcolour.png",
            width = 141,
            height = 136,
            frame_count = 1,
            repeat_count = 3,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.375,
            animation_speed = 0.5,
        }
    }
}