---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/20/2023 10:09 PM
---

return {
    run = {
        main =                     {
            filename = "__erm_toss_hd_assets__/graphics/entity/units/probe/probe-run.png",
            width = 136,
            height = 130,
            frame_count = 1,
            axially_symmetrical = false,
            direction_count = 16,
            scale =  0.3,
            animation_speed = 0.2,
        },
        shadow = {
            shift = {0.2, 0}
        },
        team = {
            filename = "__erm_toss_hd_assets__/graphics/entity/units/probe/probe-run.png",
            width = 136,
            height = 130,
            frame_count = 1,
            axially_symmetrical = false,
            direction_count = 16,
            scale =  0.3,
            animation_speed = 0.2,
        }
    },
    attack = {
        glow =                    {
            filename = "__erm_toss_hd_assets__/graphics/entity/units/probe/probe-construction-full.png",
            width = 616,
            height = 617,
            frame_count = 62,
            frame_sequence = {1,2,3,4,5,6,7,8,9,10,11,12,8,9,10,11,12,8,9,10,11,12,8,9,10,11,12,8,9,10,11,12,8,9,10,11,12,8,9,10,11,12,8,9,10,11,12,8,9,10,11,12,8,9,10,11,12,8,9,10,11,12},
            axially_symmetrical = false,
            direction_count = 1,
            animation_speed = 0.2,
            scale =  0.3,
        }
    }
}