---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/20/2023 10:09 PM
---

return {
    run = {
        main =                            {
            filename = "__erm_toss_hd_assets__/graphics/entity/units/reaver/reaver-run.png",
            width = 356,
            height = 350,
            frame_count = 9,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.4,
            animation_speed = 1,
        },
        shadow = {
            shift = {0.2, 0}
        },
        team =                            {
            filename = "__erm_toss_hd_assets__/graphics/entity/units/reaver/reaver-run_teamcolour.png",
            width = 356,
            height = 350,
            frame_count = 9,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.4,
            animation_speed = 1,
        }
    }
}