---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/20/2023 10:09 PM
---

return {
    run = {
        main =     {
            filename = "__erm_toss_hd_assets__/graphics/entity/units/scarab/scarab-run.png",
            width = 74,
            height = 83,
            frame_count = 8,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.375,
            animation_speed = 0.4
        },
        shadow = {
            shift = {0.2, 0}
        },
        glow =     {
            filename = "__erm_toss_hd_assets__/graphics/entity/units/scarab/scarab-effect.png",
            width = 74,
            height = 83,
            frame_count = 8,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.375,
            animation_speed = 0.4,
            draw_as_glow = true,
        },
        team =    {
            filename = "__erm_toss_hd_assets__/graphics/entity/units/scarab/scarab-run_teamcolour.png",
            width = 74,
            height = 83,
            frame_count = 1,
            repeat_count = 8,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.375,
            animation_speed = 0.4
        }
    }
}

