---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/20/2023 6:26 PM
---

require('util')
local AnimationDB = {}

--- Naming convention EntityType_Name. EntityType follows the graphics folder structure.
--- e.g [unit][zergling], [building][hive], [projectiles][spore], etc
---
--- death and projectile are handled differently because they are mostly single layer animation.
AnimationDB.data = {
    buildings = {
        arbiter_tribunal = require('__erm_toss_hd_assets__/db/buildings/arbiter_tribunal'),
        cannon = require('__erm_toss_hd_assets__/db/buildings/cannon'),
        citadel_adun = require('__erm_toss_hd_assets__/db/buildings/citadel_adun'),
        cybernetics_core = require('__erm_toss_hd_assets__/db/buildings/cybernetics_core'),
        fleet_beacon = require('__erm_toss_hd_assets__/db/buildings/fleet_beacon'),
        forge = require('__erm_toss_hd_assets__/db/buildings/forge'),
        gateway = require('__erm_toss_hd_assets__/db/buildings/gateway'),
        nexus = require('__erm_toss_hd_assets__/db/buildings/nexus'),
        pylon = require('__erm_toss_hd_assets__/db/buildings/pylon'),
        robotics_facility = require('__erm_toss_hd_assets__/db/buildings/robotics_facility'),
        robotics_support_bay = require('__erm_toss_hd_assets__/db/buildings/robotics_support_bay'),
        shield_battery = require('__erm_toss_hd_assets__/db/buildings/shield_battery'),
        stargate = require('__erm_toss_hd_assets__/db/buildings/stargate'),
        templar_archive = require('__erm_toss_hd_assets__/db/buildings/templar_archive'),
        warpgate = require('__erm_toss_hd_assets__/db/buildings/warpgate'),
    },
    death = require('__erm_toss_hd_assets__/db/death'),
    projectiles = require('__erm_toss_hd_assets__/db/projectiles'),
    units = {
        arbiter = require('__erm_toss_hd_assets__/db/units/arbiter'),
        archon = require('__erm_toss_hd_assets__/db/units/archon'),
        carrier = require('__erm_toss_hd_assets__/db/units/carrier'),
        corsair = require('__erm_toss_hd_assets__/db/units/corsair'),
        darkarchon = require('__erm_toss_hd_assets__/db/units/darkarchon'),
        darktemplar = require('__erm_toss_hd_assets__/db/units/darktemplar'),
        dragoon = require('__erm_toss_hd_assets__/db/units/dragoon'),
        interceptor = require('__erm_toss_hd_assets__/db/units/interceptor'),
        probe = require('__erm_toss_hd_assets__/db/units/probe'),
        reaver = require('__erm_toss_hd_assets__/db/units/reaver'),
        scarab = require('__erm_toss_hd_assets__/db/units/scarab'),
        shuttle = require('__erm_toss_hd_assets__/db/units/shuttle'),
        scout = require('__erm_toss_hd_assets__/db/units/scout'),
        templar = require('__erm_toss_hd_assets__/db/units/templar'),
        zealot = require('__erm_toss_hd_assets__/db/units/zealot'),
    }

}






---
--- Construct basic layered animations
---
function AnimationDB.get_layered_animations(entity_type, name, animation_type, unit_scale)
    return {
        layers = {
            AnimationDB.get_main_animation(entity_type, name, animation_type, unit_scale),
            AnimationDB.get_shadow_animation(entity_type, name, animation_type, unit_scale),
            AnimationDB.get_team_mask_animation(entity_type, name, animation_type, unit_scale),
            AnimationDB.get_glow_mask_animation(entity_type, name, animation_type, unit_scale),
            AnimationDB.get_effect_mask_animation(entity_type, name, animation_type, unit_scale),
            AnimationDB.get_light_mask_animation(entity_type, name, animation_type, unit_scale),
        }
    }
end

---
--- get single sprite animation
---
function AnimationDB.get_single_animation(entity_type, name, animation_type, unit_scale)
    local animation = AnimationDB.get_main_animation(entity_type, name, animation_type, unit_scale)
    return animation
end

function AnimationDB.get_main_animation(entity_type, name, animation_type, unit_scale)
    local animation = util.table.deepcopy(AnimationDB.data[entity_type][name][animation_type]['main'])
    if unit_scale then
        animation.unit_scale = unit_scale
    end
    return animation
end

function AnimationDB.get_shadow_animation(entity_type, name, animation_type, unit_scale)
    if AnimationDB.data[entity_type][name][animation_type]['shadow'] then
        local animation = AnimationDB.get_main_animation(entity_type, name, animation_type, unit_scale)
        animation['draw_as_shadow'] = true
        animation['shift'] = util.table.deepcopy(AnimationDB.data[entity_type][name][animation_type]['shadow']['shift'])
        return animation
    end
end

---
--- Return glow mask
---
function AnimationDB.get_glow_mask_animation(entity_type, name, animation_type, unit_scale)
    if AnimationDB.data[entity_type][name][animation_type]['glow'] then
        local animation = util.table.deepcopy(AnimationDB.data[entity_type][name][animation_type]['glow'])
        animation['draw_as_glow'] = true
        if unit_scale then
            animation.unit_scale = unit_scale
        end
        return animation
    end
end

---
--- Return effect mask
---
function AnimationDB.get_effect_mask_animation(entity_type, name, animation_type, unit_scale)
    if AnimationDB.data[entity_type][name][animation_type]['effect'] then
        local animation = util.table.deepcopy(AnimationDB.data[entity_type][name][animation_type]['effect'])
        if unit_scale then
            animation.unit_scale = unit_scale
        end
        return animation
    end
end

---
--- Return draw_as_light mask
---
function AnimationDB.get_light_mask_animation(entity_type, name, animation_type, unit_scale)
    if AnimationDB.data[entity_type][name][animation_type]['light'] then
        local animation = util.table.deepcopy(AnimationDB.data[entity_type][name][animation_type]['light'])
        if unit_scale then
            animation.unit_scale = unit_scale
        end
        animation['draw_as_light'] = true
        return animation
    end
end

---
--- Return color mask for team colors
---
function AnimationDB.get_team_mask_animation(entity_type, name, animation_type, unit_scale)
    if AnimationDB.data[entity_type][name][animation_type]['team'] then
        local animation = util.table.deepcopy(AnimationDB.data[entity_type][name][animation_type]['team'])
        if unit_scale then
            animation.unit_scale = unit_scale
        end
        return animation
    end
end

function AnimationDB.alter_team_color(animation_data, color, disable_mask, preserve_gloss)
    if animation_data['layers'] then
        for index, animation_node in pairs(animation_data['layers']) do
            if (animation_node.filename and string.find( animation_node.filename, '_teamcolour') ~= nil) or
                    (animation_node.filenames and string.find( animation_node.filenames[1], '_teamcolour') ~= nil) then
                if disable_mask then
                    animation_data['layers'][index] = nil
                else
                    animation_data['layers'][index]['tint'] = color
                    if preserve_gloss then
                        animation_data['layers'][index]['blend_mode'] = 'additive-soft'
                    end
                end
            end
        end
    end

    return animation_data
end

function AnimationDB.change_animation_speed(animation_data, speed)
    if animation_data['layers'] then
        for index, animation_node in pairs(animation_data['layers']) do
            if (animation_node.filename and string.find( animation_node.filename, '_teamcolour') ~= nil) or
                    (animation_node.filenames and string.find( animation_node.filenames[1], '_teamcolour') ~= nil) then
                animation_data['layers'][index]['animation_speed'] = speed
            end
        end
    elseif animation_data['animation_speed'] then
        animation_data['animation_speed'] = speed
    end

    return animation_data
end

return AnimationDB