---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/20/2023 6:30 PM
---

return {
    darkarchon = {
        explosion =
        {
            glow = {
                filename = "__erm_toss_hd_assets__/graphics/entity/units/darkarchon/darkarchon-death.png",
                width = 569,
                height = 569,
                frame_count = 12,
                direction_count = 1,
                axially_symmetrical = false,
                scale = 0.5,
                animation_speed = 0.4,
            }
        }
    },
    small_air = {
        explosion = {
            glow = {
                filename = "__erm_toss_hd_assets__/graphics/entity/units/air-death/large-air-death.png",
                width = 910,
                height = 1147,
                frame_count = 9,
                direction_count = 1,
                axially_symmetrical = false,
                scale = 0.5,
                animation_speed = 0.4,
            }
        }
    },
    large_air = {
        explosion = {
            glow = {
                filename = "__erm_toss_hd_assets__/graphics/entity/units/air-death/large-air-death.png",
                width = 910,
                height = 1147,
                frame_count = 9,
                direction_count = 1,
                axially_symmetrical = false,
                scale = 0.5,
                animation_speed = 0.4,
            }
        }
    },
    zealot = {
        explosion = {
            glow = {
                filename = "__erm_toss_hd_assets__/graphics/entity/units/zealot/zealot-death.png",
                width = 572,
                height = 568,
                frame_count = 7,
                direction_count = 1,
                axially_symmetrical = false,
                scale = 0.25,
                animation_speed = 0.4,
            }
        }
    },
    templar = {
        explosion = {
            glow = {
                filename = "__erm_toss_hd_assets__/graphics/entity/units/templar/templar-death.png",
                width = 669,
                height = 707,
                frame_count = 7,
                direction_count = 1,
                axially_symmetrical = false,
                scale = 0.25,
                animation_speed = 0.4,
            }
        }
    },
    small_building = {
        explosion = {
           glow =  {
                filename = "__erm_toss_hd_assets__/graphics/entity/buildings/death/small-building-explosion.png",
                width = 910,
                height = 1147,
                frame_count = 9,
                animation_speed = 0.4,
                direction_count = 1,
                scale = 0.5,
            }
        }
    },
    large_building = {
        explosion = {
            main =  {
                stripes =
                {
                    {
                        filename = "__erm_toss_hd_assets__/graphics/entity/buildings/death/large-building-explosion-0.png",
                        width_in_frames = 2,
                        height_in_frames = 1
                    },
                    {
                        filename = "__erm_toss_hd_assets__/graphics/entity/buildings/death/large-building-explosion-1.png",
                        width_in_frames = 2,
                        height_in_frames = 1
                    },
                    {
                        filename = "__erm_toss_hd_assets__/graphics/entity/buildings/death/large-building-explosion-2.png",
                        width_in_frames = 2,
                        height_in_frames = 1
                    },
                    {
                        filename = "__erm_toss_hd_assets__/graphics/entity/buildings/death/large-building-explosion-3.png",
                        width_in_frames = 2,
                        height_in_frames = 1
                    },
                    {
                        filename = "__erm_toss_hd_assets__/graphics/entity/buildings/death/large-building-explosion-4.png",
                        width_in_frames = 2,
                        height_in_frames = 1
                    },
                    {
                        filename = "__erm_toss_hd_assets__/graphics/entity/buildings/death/large-building-explosion-5.png",
                        width_in_frames = 2,
                        height_in_frames = 1
                    },
                    {
                        filename = "__erm_toss_hd_assets__/graphics/entity/buildings/death/large-building-explosion-6.png",
                        width_in_frames = 2,
                        height_in_frames = 1
                    },
                    {
                        filename = "__erm_toss_hd_assets__/graphics/entity/buildings/death/large-building-explosion-7.png",
                        width_in_frames = 2,
                        height_in_frames = 1
                    }
                },
                width = 1849,
                height = 1935,
                frame_count = 16,
                animation_speed = 0.4,
                direction_count = 1,
                scale = 0.5,
            }
        }
    }
}

