---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/20/2023 6:30 PM
---

return {
    darkarchon = {
        explosion =
        {
            glow = {
                filename = "__erm_toss_hd_assets__/graphics/entity/units/darkarchon/darkarchon-death.png",
                width = 569,
                height = 569,
                frame_count = 12,
                direction_count = 1,
                axially_symmetrical = false,
                scale = 0.5,
                animation_speed = 0.4,
            }
        }
    },
    small_air = {
        explosion = {
            glow = {
                filename = "__erm_toss_hd_assets__/graphics/entity/units/air-death/small-air-death.png",
                width = 899,
                height = 1057,
                frame_count = 9,
                direction_count = 1,
                axially_symmetrical = false,
                scale = 0.5,
                animation_speed = 0.4,
            }
        }
    },
    zealot = {
        explosion = {
            glow = {
                filename = "__erm_toss_hd_assets__/graphics/entity/units/zealot/zealot-death.png",
                width = 572,
                height = 568,
                frame_count = 7,
                direction_count = 1,
                axially_symmetrical = false,
                scale = 0.25,
                animation_speed = 0.4,
            }
        }
    },
    templar = {
        explosion = {
            glow = {
                filename = "__erm_toss_hd_assets__/graphics/entity/units/templar/templar-death.png",
                width = 669,
                height = 707,
                frame_count = 7,
                direction_count = 1,
                axially_symmetrical = false,
                scale = 0.25,
                animation_speed = 0.4,
            }
        }
    },
    small_building = {
        explosion = {
           glow =  {
                filename = "__erm_toss_hd_assets__/graphics/entity/buildings/building_death/small-building-explosion.png",
                width = 910,
                height = 1147,
                frame_count = 9,
                animation_speed = 0.4,
                direction_count = 1,
                scale = 0.5,
            }
        }
    },
    large_building = {
        explosion = {
            glow =  {
                filename = "__erm_toss_hd_assets__/graphics/entity/buildings/building_death/large-building-explosion.png",
                width = 1849,
                height = 1935,
                line_length = 4,
                frame_count = 16,
                animation_speed = 0.25,
                direction_count = 1,
                scale = 0.5,
            }
        }
    },
    small_rubble = {
        explosion = {
            main =  {
                filename = "__erm_toss_hd_assets__/graphics/entity/buildings/building_death/small_rubble.png",
                variation_count = 1,
                width = 353,
                height = 376,
                frame_count = 1,
                direction_count = 1,
                scale = 0.5
            }
        }
    },
    large_rubble = {
        explosion = {
            main =  {
                filename = "__erm_toss_hd_assets__/graphics/entity/buildings/building_death/large_rubble.png",
                width = 502,
                height = 533,
                variation_count = 1,
                frame_count = 1,
                direction_count = 1,
                scale = 0.5
            }
        }
    }
}

