---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/24/2023 8:08 PM
---

return {
    run = {
        main =      {
            filename = "__erm_toss_hd_assets__/graphics/entity/buildings/arbiter_tribunal/arbiter_tribunal.png",
            width = 383,
            height = 510,
            frame_count = 4,
            animation_speed = 0.2,
            direction_count = 1,
            run_mode = "forward-then-backward",
            scale = 0.5
        },
        shadow = {
            shift = { 0.25, 0.1 },
        },
        glow =     {
            filename = "__erm_toss_hd_assets__/graphics/entity/buildings/arbiter_tribunal/arbiter_tribunal_mask.png",
            width = 383,
            height = 510,
            frame_count = 4,
            animation_speed = 0.2,
            direction_count = 1,
            run_mode = "forward-then-backward",
            scale = 0.5,
            draw_as_glow = true,
            blend_mode = "additive-soft",
        },
        team = {
            filename = "__erm_toss_hd_assets__/graphics/entity/buildings/arbiter_tribunal/arbiter_tribunal_teamcolour.png",
            width = 381,
            height = 508,
            frame_count = 1,
            repeat_count = 8,
            animation_speed = 0.2,
            direction_count = 1,
            scale = 0.5
        }
    }
}