---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/24/2023 7:35 PM
---

return {
    run = {
        main =     {
            filename = "__erm_toss_hd_assets__/graphics/entity/buildings/cannon/cannon.png",
            width = 256,
            height = 518,
            frame_count = 1,
            direction_count = 1,
            animation_speed = 0.2,
            scale = 0.5,
        },
        shadow = {
            shift = { 0.25, 0.1 },
        },
        glow =     {
            filename = "__erm_toss_hd_assets__/graphics/entity/buildings/cannon/cannon_mask.png",
            width = 256,
            height = 518,
            frame_count = 1,
            direction_count = 1,
            scale = 0.5,
            animation_speed = 0.2,
            blend_mode = "additive-soft",
            draw_as_glow = true,
        }
    },
    attack = {
        main =     {
            filename = "__erm_toss_hd_assets__/graphics/entity/buildings/cannon/cannon_attack.png",
            width = 258,
            height = 520,
            frame_count = 3,
            direction_count = 1,
            scale = 0.5,
            run_mode = "forward-then-backward",
            animation_speed = 0.2,
        },
        shadow = {
            shift = { 0.25, 0.1 },
        },
        glow =      {
            filename = "__erm_toss_hd_assets__/graphics/entity/buildings/cannon/cannon_attack_mask.png",
            width = 258,
            height = 520,
            frame_count = 3,
            direction_count = 1,
            scale = 0.5,
            run_mode = "forward-then-backward",
            animation_speed = 0.2,
            blend_mode = "additive-soft",
            draw_as_glow = true,
        }
    }
}