---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/24/2023 8:08 PM
---

return {
    run = {
        main =     {
            filename = "__erm_toss_hd_assets__/graphics/entity/buildings/citadel_adun/citadel_adun.png",
            width = 640,
            height = 518,
            frame_count = 1,
            animation_speed = 0.2,
            direction_count = 1,
            scale = 0.5
        },
        shadow = {
            shift = { 0.25, 0.1 },
        },
        glow =     {
            filename = "__erm_toss_hd_assets__/graphics/entity/buildings/citadel_adun/citadel_adun_mask.png",
            width = 640,
            height = 518,
            frame_count = 1,
            animation_speed = 0.2,
            direction_count = 1,
            scale = 0.5,
            draw_as_glow = true,
            blend_mode = "additive-soft",
        },
        team =     {
            filename = "__erm_toss_hd_assets__/graphics/entity/buildings/citadel_adun/citadel_adun_teamcolour.png",
            width = 640,
            height = 518,
            frame_count = 1,
            animation_speed = 0.18,
            direction_count = 1,
            scale = 0.5
        },
    }
}