---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/24/2023 8:08 PM
---

return {
    run = {
        main =      {
            filename = "__erm_toss_hd_assets__/graphics/entity/buildings/cybernetics_core/cybernetics_core.png",
            width = 383,
            height = 516,
            frame_count = 3,
            animation_speed = 0.2,
            direction_count = 1,
            scale = 0.5
        },
        shadow = {
            shift = { 0.25, 0.1 },
        },
        glow =     {
            filename = "__erm_toss_hd_assets__/graphics/entity/buildings/cybernetics_core/cybernetics_core_mask.png",
            width = 383,
            height = 516,
            frame_count = 3,
            animation_speed = 0.2,
            direction_count = 1,
            scale = 0.5,
            draw_as_glow = true,
            blend_mode = "additive-soft",
        },
        team =      {
            filename = "__erm_toss_hd_assets__/graphics/entity/buildings/cybernetics_core/cybernetics_core_teamcolour.png",
            width = 383,
            height = 516,
            frame_count = 1,
            repeat_count = 3,
            animation_speed = 0.2,
            direction_count = 1,
            scale = 0.5
        },
    }
}