---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/24/2023 8:08 PM
---
return {
    run = {
        main =      {
            filename = "__erm_toss_hd_assets__/graphics/entity/buildings/fleet_beacon/fleet_beacon.png",
            width = 773,
            height = 649,
            frame_count = 1,
            animation_speed = 0.2,
            direction_count = 1,
            scale = 0.5
        },
        shadow = {
            shift = { 0.25, 0 },
        },
        glow =     {
            filename = "__erm_toss_hd_assets__/graphics/entity/buildings/fleet_beacon/fleet_beacon_mask.png",
            width = 773,
            height = 649,
            frame_count = 1,
            animation_speed = 0.2,
            direction_count = 1,
            scale = 0.5,
            draw_as_glow = true,
            blend_mode = "additive-soft",
        },
        team = {
            filename = "__erm_toss_hd_assets__/graphics/entity/buildings/fleet_beacon/fleet_beacon_teamcolour.png",
            width = 773,
            height = 649,
            frame_count = 1,
            animation_speed = 0.2,
            direction_count = 1,
            scale = 0.5
        }

    }
}