---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/24/2023 8:08 PM
---

return {
    run = {
        main =      {
            filename = "__erm_toss_hd_assets__/graphics/entity/buildings/gateway/gateway.png",
            width = 522,
            height = 673,
            frame_count = 1,
            animation_speed = 0.2,
            direction_count = 1,
            scale = 0.5
        },
        shadow = {
            shift = { 0.25, 0.1 },
        },
        glow = {
            filename = "__erm_toss_hd_assets__/graphics/entity/buildings/gateway/gateway_mask.png",
            width = 522,
            height = 673,
            frame_count = 1,
            animation_speed = 0.2,
            direction_count = 1,
            scale = 0.5,
            draw_as_glow = true,
            blend_mode = "additive-soft",
        }
    }
}