---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/24/2023 8:08 PM
---

return {
    run = {
        main =      {
            filename = "__erm_toss_hd_assets__/graphics/entity/buildings/pylon/pylon.png",
            width = 253,
            height = 258,
            frame_count = 1,
            animation_speed = 0.2,
            direction_count = 1,
            scale = 0.5
        },
        shadow = {
            shift = { 0.25, 0.1 },
        },
        light = {
            filename = "__erm_toss_hd_assets__/graphics/entity/buildings/pylon/pylon_mask.png",
            width = 253,
            height = 258,
            frame_count = 1,
            animation_speed = 0.2,
            direction_count = 1,
            scale = 0.5
        },
        team =      {
            filename = "__erm_toss_hd_assets__/graphics/entity/buildings/pylon/pylon_teamcolour.png",
            width = 253,
            height = 258,
            frame_count = 1,
            animation_speed = 0.2,
            direction_count = 1,
            scale = 0.5
        },
    },
    integration_patch = {
        main =  {
            filename = "__erm_toss_hd_assets__/graphics/entity/buildings/pylon/pylon_field.png",
            width = 1000,
            height = 512,
            frame_count = 1,
            animation_speed = 0.18,
            direction_count = 1,
            blend_mode = "additive",
            tint = {100, 100, 255},
            draw_as_glow = true,
            shift = {0.0, 2},
            scale = 1
        }
    }
}