---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/24/2023 8:08 PM
---

return {
    run = {
        main =                     {
            filename = "__erm_toss_hd_assets__/graphics/entity/buildings/robotics_facility/robotics_facility.png",
            width = 386,
            height = 512,
            frame_count = 1,
            animation_speed = 0.2,
            direction_count = 1,
            scale = 0.5
        },
        shadow = {
            shift = { 0.25, 0 },
        },
        glow = {
            filename = "__erm_toss_hd_assets__/graphics/entity/buildings/robotics_facility/robotics_facility_mask.png",
            width = 386,
            height = 512,
            frame_count = 1,
            animation_speed = 0.2,
            direction_count = 1,
            scale = 0.5,
            draw_as_glow = true,
            blend_mode = "additive-soft",
        },
        team = {
            filename = "__erm_toss_hd_assets__/graphics/entity/buildings/robotics_facility/robotics_facility_teamcolour.png",
            width = 386,
            height = 512,
            frame_count = 1,
            animation_speed = 0.2,
            direction_count = 1,
            scale = 0.5
        }
    }
}