---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/24/2023 7:35 PM
---

return {
    folded = {
        main =             {
            filename = "__erm_toss_hd_assets__/graphics/entity/buildings/shield_battery/shield_battery.png",
            variation_count = 1,
            width = 375,
            height = 253,
            frame_count = 1,
            direction_count = 1,
            animation_speed = 0.2,
            scale = 0.5
        },
        shadow = {
            shift = { 0.25, 0 },
        },
        glow =             {
            filename = "__erm_toss_hd_assets__/graphics/entity/buildings/shield_battery/shield_battery_mask.png",
            width = 375,
            height = 253,
            frame_count = 1,
            direction_count = 1,
            animation_speed = 0.2,
            scale = 0.5,
            draw_as_glow = true,
            blend_mode = "additive-soft",
        },
        team = {
            filename = "__erm_toss_hd_assets__/graphics/entity/buildings/shield_battery/shield_battery_teamcolour.png",
            variation_count = 1,
            width = 375,
            height = 253,
            frame_count = 1,
            direction_count = 1,
            animation_speed = 0.2,
            scale = 0.5
        }
    },
    attack = {
        main =             {
            filename = "__erm_toss_hd_assets__/graphics/entity/buildings/shield_battery/shield_battery.png",
            variation_count = 1,
            width = 375,
            height = 253,
            frame_count = 1,
            repeat_count = 3,
            direction_count = 1,
            animation_speed = 0.2,
            scale = 0.5
        },
        shadow = {
            shift = { 0.25, 0 },
        },
        glow =             {
            filename = "__erm_toss_hd_assets__/graphics/entity/buildings/shield_battery/shield_battery_effect.png",
            width = 375,
            height = 253,
            frame_count = 3,
            direction_count = 1,
            scale = 0.5,
            animation_speed = 0.2,
            draw_as_glow = true,
            blend_mode = "additive-soft",
            shift = util.by_pixel(0,-8)
        },
        team = {
            filename = "__erm_toss_hd_assets__/graphics/entity/buildings/shield_battery/shield_battery_teamcolour.png",
            variation_count = 1,
            width = 375,
            height = 253,
            frame_count = 1,
            repeat_count = 3,
            direction_count = 1,
            animation_speed = 0.2,
            scale = 0.5
        }
    }
}