---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/24/2023 7:35 PM
---

return {
    run = {
        main =                     {
            filename = "__erm_toss_hd_assets__/graphics/entity/buildings/templar_archive/templar_archive.png",
            variation_count = 1,
            width = 642,
            height = 787,
            frame_count = 1,
            line_length = 1,
            animation_speed = 0.2,
            scale = 0.5
        },
        shadow = {
            shift = { 0.25, 0.1 },
        },
        glow =                     {
            filename = "__erm_toss_hd_assets__/graphics/entity/buildings/templar_archive/templar_archive_mask.png",
            width = 642,
            height = 787,
            frame_count = 1,
            animation_speed = 0.2,
            direction_count = 1,
            draw_as_glow = true,
            blend_mode = "additive-soft",
            scale = 0.5
        }
    }
}