---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/24/2023 9:31 PM
---

return {
    run = {
        main =     {
            filename = "__erm_toss_hd_assets__/graphics/entity/buildings/warpgate/warpgate.png",
            width = 627,
            height = 969,
            frame_count = 1,
            repeat_count = 6,
            animation_speed = 0.2,
            direction_count = 1,
            scale = 0.5,
        },
        shadow = {
            shift = { 0.25, 0.1 },
        },
        glow =     {
            filename = "__erm_toss_hd_assets__/graphics/entity/buildings/warpgate/warpgate_mask.png",
            width = 627,
            height = 969,
            frame_count = 1,
            repeat_count = 6,
            animation_speed = 0.2,
            direction_count = 1,
            scale = 0.5,
            blend_mode = "additive",
            draw_as_glow = true,
        },
        effect = {
            filename = "__erm_toss_hd_assets__/graphics/entity/buildings/warpgate/warpgate_effect.png",
            width = 627,
            height = 969,
            frame_count = 6,
            animation_speed = 0.2,
            direction_count = 1,
            scale = 0.5,
            draw_as_glow = true,
        }
    }
}